apiVersion: v1
clusters:
- cluster:
    server: https://cedille.kubernetes.omni.siderolabs.io
  name: cedille-cedille-cluster-terraform01
contexts:
- context:
    cluster: cedille-cedille-cluster-terraform01
    namespace: default
    user: cedille-cedille-cluster-terraform01
  name: cedille-cedille-cluster-terraform01
current-context: cedille-cedille-cluster-terraform01
kind: Config
preferences: {}
users:
- name: cedille-cedille-cluster-terraform01
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVhMThhZDczLTMwNjMtNGMyNS1hMDhhLWQ0NmUyMGUyYThhOCIsInR5cCI6IkpXVCJ9.eyJjbHVzdGVyIjoiY2VkaWxsZS1jbHVzdGVyIiwiZXhwIjoxNzI2NTIyNjA3LCJncm91cHMiOlsic3lzdGVtOm1hc3RlcnMiXSwiaWF0IjoxNjk0OTg2NjA3LCJpc3MiOiJvbW5pLWNlZGlsbGUtc2VydmljZS1hY2NvdW50LWlzc3VlciIsInN1YiI6InRlcnJhZm9ybTAxIn0.SuMYqorkEhUZA3PaAYyCEZslvmnuPulX0bz5CViE9j-9l9JkUdkQWnys365AeuglnFdfM-IHn93-gh-rhGpp547GyQdxl72voBAjAFSd0gfQZmzed_ot8cKyWUHtkpBxmHTt1Y2gtrySdokATjR0n8MohHfyFGFTHZZwX6QLk9HGYdvAM8jl8aJleGtPsefSq_tRCXViZbG6iR_O9kNjwnd6iX0mw8xbvuLH0-8hSeVhQrwU5FipGdvQks7e_9N0_1m07Yz5Qcx0II6yPeToznOk0tYMwfu5EkCiXXmqQFTZQwg3oBm4RjY4DepPYQOg2EAd-_xjmZoY_jAtpWUizA
